"""Standalone, runnable demo for Autonomous Similar-Incident Retrieval.

Usage:
    python demo_incident_retrieval.py

This builds a tiny throwaway corpus, indexes it with the real FOX builder,
then submits an alert two ways:
  1. Plain FOX search (no Gemini) - shows the baseline miss.
  2. Gemini-assisted query expansion - shows the same alert now finding the
     historical incident, via terms Gemini proposes.

If GEMINI_API_KEY is set in the environment, this calls the real Gemini API.
Otherwise it falls back to a canned MockGemini so the demo still runs offline.
"""

from __future__ import annotations

import os
import subprocess
import sys
import tempfile
from pathlib import Path

from autocomplete.incident_retrieval.retrieval import retrieve_similar_incidents
from autocomplete.incident_retrieval.schema import IncidentRequest, SearchConcepts
from autocomplete.search_engine import SearchEngine
from autocomplete.snapshot_loader import load_snapshot

REPO_ROOT = Path(__file__).parent
REFERENCE_BUILDER = REPO_ROOT / "tests" / "reference_builder.py"


class MockGemini:
    """Used only when GEMINI_API_KEY is not set, so the demo works offline."""

    def expand(self, request: IncidentRequest) -> SearchConcepts:
        return SearchConcepts(
            [
                "optical link degradation",
                "formation drift",
                "communication throughput loss",
            ]
        )


def build_demo_snapshot(tmp_dir: Path) -> Path:
    corpus = tmp_dir / "corpus"
    sat03 = corpus / "sat_03" / "communication_logs.txt"
    sat03.parent.mkdir(parents=True)
    sat03.write_text(
        "Nominal communication state\n"
        "Formation drift caused optical link degradation\n"
        "Battery cycle complete\n"
    )
    sat05 = corpus / "sat_05" / "power_logs.txt"
    sat05.parent.mkdir(parents=True)
    sat05.write_text(
        "HBM irregularity followed proton radiation exposure\n"
        "TPU temperature exceeded the safe operating threshold\n"
    )
    snapshot = tmp_dir / "snapshot"
    subprocess.run(
        [sys.executable, str(REFERENCE_BUILDER), str(corpus), str(snapshot)],
        check=True,
        capture_output=True,
        text=True,
    )
    return snapshot


def print_response(title: str, response) -> None:
    print(f"\n--- {title} ---")
    if response.generated is not None:
        print(f"Generated by Gemini: {response.generated.search_terms}")
    else:
        print("Generated by Gemini: (none - fallback mode)")
    print(f"used_fallback: {response.used_fallback}")
    if response.retrieved:
        for item in response.retrieved:
            print(
                f"Retrieved by FOX: \"{item.corpus_sentence}\" "
                f"[source={item.source_file}:{item.line_number}, "
                f"satellite={item.satellite_id}, score={item.fox_score}]"
            )
    else:
        print(f"Retrieved by FOX: {response.evidence_message}")


def get_client():
    api_key = os.environ.get("GEMINI_API_KEY")
    if not api_key:
        print("(No GEMINI_API_KEY set - using an offline mock Gemini client)")
        return MockGemini()
    from autocomplete.incident_retrieval.gemini_client import GeminiClient

    client = GeminiClient.from_environment()
    if client is None:
        print("(GeminiClient.from_environment() returned None - using mock)")
        return MockGemini()
    print("(Using the real Gemini API)")
    return client


def main() -> None:
    with tempfile.TemporaryDirectory() as tmp:
        snapshot = build_demo_snapshot(Path(tmp))
        records, index = load_snapshot(snapshot)
        engine = SearchEngine(records, index)

        request = IncidentRequest(
            satellite_id="SAT-07",
            subsystem="OPTICAL_LINK",
            severity="CRITICAL",
            description="The satellites moved apart and data transfer became weak.",
        )
        print(f"Incoming alert: {request.description!r} (from {request.satellite_id})")

        plain = retrieve_similar_incidents(request, search=engine.search)
        print_response("1. Plain FOX search (no Gemini)", plain)

        client = get_client()
        expanded = retrieve_similar_incidents(request, client, engine.search)
        print_response("2. Gemini-assisted query expansion", expanded)

        print("\n--- 3. Fallback behavior when Gemini fails ---")

        class BrokenGemini:
            def expand(self, request: IncidentRequest) -> SearchConcepts:
                raise RuntimeError("simulated network timeout")

        broken = retrieve_similar_incidents(request, BrokenGemini(), engine.search)
        print_response("Gemini raised an error -> automatic fallback", broken)


if __name__ == "__main__":
    main()
